flowchart LR

    BD["Base de Datos<br/>Guarda: Sedes, Reservas y Usuarios"]

    MENU["Menú de Sitios<br/>Restaurante"]

    SITIOS["Sitios<br/>Sedes del Restaurante"]

    RESERVAS["Reservas<br/>Ingreso de datos para crear la reserva"]

    CONFIRMACION["Confirmación de Reserva<br/>Muestra datos y permite enviar confirmación"]

    ADMIN["Administración<br/>Visualiza todas las reservas y sus datos"]

    DETALLES["Detalles<br/>Estados: Confirmada, Pendiente, Cancelada"]

    BD --> MENU
    MENU --> SITIOS
    SITIOS --> RESERVAS
    SITIOS --> ADMIN
    RESERVAS --> CONFIRMACION
    ADMIN --> DETALLES