# Generated by Django 6.0.6 on 2026-07-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='negocio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/'),
        ),
    ]
