# Generated by Django 6.0.6 on 2026-07-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0002_remove_negocio_imagen_url_negocio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='imagen',
        ),
        migrations.AddField(
            model_name='negocio',
            name='imagen_hero',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/heroes/'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='imagen_miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/miniaturas/'),
        ),
    ]
