# Generated by Django 6.0.7 on 2026-07-18 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0003_remove_negocio_imagen_negocio_imagen_hero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('usuario_sesion', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reservas.negocio')),
            ],
            options={
                'db_table': 'app_reservas_reservatemporal',
            },
        ),
    ]
