# Generated by Django 6.0.6 on 2026-07-07 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0002_reservatemporal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariodisponible',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='reserva',
            name='reservas_fecha_b08747_idx',
        ),
        migrations.RemoveIndex(
            model_name='reserva',
            name='reservas_estado_0b2aee_idx',
        ),
        migrations.RemoveIndex(
            model_name='reserva',
            name='reservas_negocio_61743f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='horariodisponible',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='horariodisponible',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='app_reservas.negocio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='comensales',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='email_cliente',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombre_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='ocasion',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('cumpleanos', 'Cumpleaños'), ('aniversario', 'Aniversario'), ('otro', 'Otro')], default='ninguna', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservatemporal',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reservas.negocio'),
        ),
        migrations.AlterModelTable(
            name='horariodisponible',
            table=None,
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='horariodisponible',
            name='cupo_maximo',
        ),
        migrations.RemoveField(
            model_name='horariodisponible',
            name='cupo_ocupado',
        ),
        migrations.RemoveField(
            model_name='horariodisponible',
            name='fecha',
        ),
    ]
